#!/bin/bash
# A modification of https://github.com/trilinos/Trilinos/blob/master/sampleScripts/do-configure-mkl-mpi-gcc-linux (Mark Hoemmen <mhoemme AT sandia DOT gov>
#
# Example CMake configure script for Trilinos, that uses Intel's Math
# Kernel Library (MKL) both for the BLAS and LAPACK implementation,
# and as a separate MKL TPL (Third-Party Library).  Specifically, in
# this case, we're using the MKL for its sparse matrix kernels.  Here
# are other details of my configuration:
#
# Operating system: GFreya OS
# Compiler: gcc (version 11.2.0, user-space installation)
# MPI version: OpenMPI 4.1.3 (user-space installation)
# Other TPLs: 
# - Boost (optional, version 1.50.0, user-space installation)
# - OpenMP (optional)
#
######################################################################


# Script magic to pull in my user-space install of gcc.
concat_path () {
    if ! echo $PATH | /bin/egrep -q "(^|:)$1($|:)" ; then
	if [ "$2" = "after" ] ; then
	    PATH=$PATH:$1
	else
	    PATH=$1:$PATH
	fi
    fi
    export PATH
}

# Script magic to pull in my user-space install of gcc.
concat_ld_library_path () {
    if ! echo $LD_LIBRARY_PATH | /bin/egrep -q "(^|:)$1($|:)" ; then
	if [ "$2" = "after" ] ; then
	    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$1
	else
	    LD_LIBRARY_PATH=$1:$LD_LIBRARY_PATH
	fi
    fi
    export LD_LIBRARY_PATH
}

# Script magic to pull in my user-space install of gcc.
# For some odd reason, the exports don't escape this script.
if [ -d $HOME/pkg/gcc-4.5.1/lib64 ]; then
    concat_ld_library_path $HOME/pkg/gcc-4.5.1/lib64
else
    concat_ld_library_path $HOME/pkg/gcc-4.5.1/lib
fi
concat_path $HOME/pkg/gcc-4.5.1/bin

# Pull in any extra arguments given to this script.
# Treat them as extra CMake options.
EXTRA_ARGS=$@

# Point to the user-space install of OpenMPI (MPI implementation).
MPI_ROOT=/opt/hamzstlib/
MPI_BIN=$MPI_ROOT/bin

cmake \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  -D CMAKE_BUILD_TYPE:STRING=DEBUG \
  -D CMAKE_INSTALL_PREFIX:FILEPATH="/opt/hamzstlib/trilinos" \
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D MPI_BASE_DIR="/opt/hamzstlib" \
  -D MPI_EXEC:FILEPATH="/opt/hamzstlib/bin/mpiexec" \
  -D MPI_Fortran_COMPILER:FILEPATH="${MPI_BIN}/mpif90" \
  -D MPI_CXX_COMPILER:FILEPATH="${MPI_BIN}/mpicxx" \
  -D MPI_C_COMPILER:FILEPATH="${MPI_BIN}/mpicc" \
  -D CMAKE_CXX_FLAGS:STRING="-ansi -pedantic -Wall" \
  -D BLAS_LIBRARY_DIRS:FILEPATH="/opt/hamzstlib/lib" \
  -D BLAS_LIBRARY_NAMES:STRING="blas" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH="/opt/hamzstlib/lib" \
  -D LAPACK_LIBRARY_NAMES:STRING="lapack" \
  -D TPL_ENABLE_MKL:BOOL=OFF \
  -D Trilinos_ENABLE_OpenMP:BOOL=ON \
  -D TPL_ENABLE_Pthread:BOOL=ON \
  -D TPL_ENABLE_Boost:BOOL=ON \
  -D Boost_LIBRARY_DIRS:FILEPATH="/usr/lib" \
  -D Boost_INCLUDE_DIRS:FILEPATH="/usr/include" \
  -D DART_TESTING_TIMEOUT:STRING=600 \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_Teuchos=ON \
  -D Trilinos_ENABLE_Tpetra=ON \
  -D Trilinos_ENABLE_Epetra=ON \
  -D Trilinos_ENABLE_EpetraExt=ON \
  -D Trilinos_ENABLE_Anasazi=ON \
  -D Trilinos_ENABLE_Amesos2=ON \
  -D Trilinos_ENABLE_Belos=ON \
  -D Trilinos_ENABLE_Galeri=ON \
  -D Trilinos_ENABLE_Ifpack=ON \
  -D Trilinos_ENABLE_Ifpack2=ON \
  -D Trilinos_ENABLE_Kokkos=ON \
  -D Trilinos_ENABLE_KokkosKernels=ON \
  -D Trilinos_ENABLE_Komplex=ON \
  -D Trilinos_ENABLE_MueLu=ON \
  -D Trilinos_ENABLE_MOOCHO=ON \
  -D Trilinos_ENABLE_NOX=ON \
  -D Trilinos_ENABLE_Rythmos=ON \
  -D Trilinos_ENABLE_Stratimikos=ON \
  -D Trilinos_ENABLE_Teko=ON \
  -D Trilinos_ENABLE_Tempus=ON \
  -D Trilinos_ENABLE_Thyra=ON \
  -D Trilinos_ENABLE_TESTS:BOOL=ON \
  -D Trilinos_ENABLE_DEBUG:BOOL=ON \
  -D Trilinos_ENABLE_Xpetra:BOOL=ON \
  -D Teuchos_ENABLE_COMPLEX:BOOL=ON \
  -D Teuchos_ENABLE_EXAMPLES:BOOL=ON \
  -D Teuchos_ENABLE_TESTS:BOOL=ON \
  -D Kokkos_ENABLE_EXAMPLES:BOOL=ON \
  -D Kokkos_ENABLE_TESTS:BOOL=ON \
  -D Kokkos_ENABLE_TSQR:BOOL=ON \
  -D TSQR_ENABLE_Fortran:BOOL=ON \
  -D Tpetra_ENABLE_TESTS:BOOL=ON \
  -D Tpetra_ENABLE_BUGTESTS:BOOL=OFF \
  -D Tpetra_ENABLE_EXAMPLES:BOOL=ON \
  -D Tpetra_PRINT_Efficiency_Warnings:BOOL=ON \
  -D TPL_ENABLE_Netcdf=OFF \
  $EXTRA_ARGS \
  ../Trilinos

